// ⚠️  ARCHIVO GENERADO por scripts/buildData.mjs — NO EDITAR A MANO.
// Se regenera en cada build a partir del Google Sheet + Cloudinary.

import type { Property } from './types'

export const generatedProperties: Property[] = [
  {
    "id": 1,
    "city": "Barcelona",
    "zone": "l'Eixample",
    "title": "Piso en venta en Carrer Consell de Cent - La Nova Esquerra de l'Eixample",
    "beds": 4,
    "baths": 2,
    "m2": 124,
    "price": 549000,
    "priceLabel": "549.000 €",
    "mode": "compra",
    "category": "piso",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/cover_yd6ija",
    "desc": "Grorp Casas presenta piso de 124 m2 en venta situado en el corazon de l'Eixample, Barcelona. Finca con ascensor, combina arquitectura clasica con comodidades actuales. 4 habitaciones, una tipo suite con bano privado. Bano completo reformado hace un ano. Amplio salon comedor con salida a balcon. Cocina office con peninsula. Suelos de marmol, calefaccion por gas natural y aire acondicionado por conductos. A 5 min de Rocafort, 15 min de Plaza Espana y Plaza Catalunya. No te pierdas esta oportunidad. ¡Ven a verlo! Los honorarios de la agencia intermediadora y los gastos de compra-venta no están incluidos en el precio.",
    "features": [
      "Ascensor"
    ],
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/cover_yd6ija",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/01-salon_hmsbjg",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/02-salon_fcazay",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/03-habitacion_matrimonio_uh4fq4",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/04-habitacionmatrimonio_xbqngn",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/05-habitacion2_lwvooj",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/06-habitacion2_nm14qj",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/07-habitacion3_klj8hl",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/08-habitacion_r0ide0",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/09_vestidor_xrvt99",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/10_lavanderia_wrp8dw",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/11_baño_ybcdzn",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/12_baños1_yxs5ds"
    ],
    "coords": {
      "lat": 41.385,
      "lng": 2.154
    },
    "status": "EN VENTA",
    "cert": "D",
    "dateAdded": "2026-02-26"
  },
  {
    "id": 9,
    "city": "Esplugues de Llobregat",
    "zone": "Can Vidalet",
    "title": "Piso en venta en Calle de la Maladeta, Can Vidalet - Esplugues de Llobregat",
    "beds": 3,
    "baths": 1,
    "m2": 60,
    "price": 140000,
    "priceLabel": "140.000 €",
    "mode": "compra",
    "category": "piso",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/cover_iqca85",
    "desc": "Group Casas presenta piso en venta exterior luminoso en buen estado en la zona de Can Vidalet, Esplugues de Llobregat. A tan solo un minuto de la linea azul, Can Vidalet (L5), y 5 minutos del tranvía parada Can Oliveres, rodeado de zonas verdes, supermercados y escuelas.\n\nConsta de: 60 m2 construidos que se dividen en un amplio salón comedor luminoso y cocina, tres habitaciones, dos dobles y una individual y un baño.\nFinca sin ascensor.\n// Vivienda actualmente alquilada, renovable año a año// // Las imágenes mostradas son una propuesta visual de cómo podría verse la vivienda decorada. La estructura, distribución y espacios del piso pueden ser exactamente iguales //\n\nNo te pierdas esta oportunidad. ¡Ven a verlo! Honorarios de la agencia y gastos de compraventa no están incluidos en el precio.",
    "features": [],
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/cover_iqca85",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/1.salon_rmovie",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/2.habitacion_u7oijg",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/3.habitacion_iqvccn",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/4.habitación_vjtbce",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/5.habitación_uigeju"
    ],
    "coords": {
      "lat": 41.375,
      "lng": 2.088
    },
    "status": "EN VENTA",
    "dateAdded": "2026-01-26"
  },
  {
    "id": 13,
    "city": "Barcelona",
    "zone": "Pedralbes",
    "title": "Casa / Chalet independiente en venta en Avenida de Pearson 49 - Pedralbes",
    "beds": 7,
    "baths": 5,
    "m2": 700,
    "price": 8500000,
    "priceLabel": "8.500.000 €",
    "mode": "compra",
    "category": "chalet",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/cover_xx2gpc",
    "desc": "Group Casas presenta este excepcional chalet independiente en Pedralbes, una de las zonas residenciales más prestigiosas y codiciadas de Barcelona.\nSe trata de una villa única, de marcada personalidad arquitectónica, proyectada por Francesc Mitjans, uno de los arquitectos más influyentes y reconocidos de la ciudad.\n\nLa vivienda disfruta de maravillosas vistas abiertas sobre toda la ciudad y se asienta sobre una parcela completamente llana, un valor excepcional en la zona, que permite disfrutar plenamente del jardín y de la vida exterior.\n\nDistribución:\n\nEn planta baja, la casa se organiza en torno a un sofisticado conjunto de salón–comedor–biblioteca y cocina, con amplios ventanales y una agradable continuidad hacia el exterior. Desde esta zona se accede directamente al jardín privado, uno de los grandes atractivos de la propiedad, que integra piscina, zonas de descanso y espacios ideales para reuniones sociales y eventos.\n\nEn esta misma planta se encuentra una zona de invitados independiente, compuesta por salón privado y dos dormitorios en suite, que garantiza total privacidad y confort.\n\nLa planta superior alberga la espectacular master suite, con dos vestidores, un acogedor salón privado y vistas despejadas, además de dos dormitorios adicionales en suite.\nUna escalera de diseño, premiada arquitectónicamente, conecta las plantas y refuerza el carácter singular y exclusivo de la vivienda.\n\nEn total, la casa dispone de 7 dormitorios, 5 baños completos y 2 aseos de cortesía, además de una zona de servicio con lavandería, plancha y entrada independiente, situada junto a una espectacular cocina pensada para el día a día y para grandes recepciones.\n\nComodidades y exteriores:\n\nLa propiedad cuenta con dos áreas de aparcamiento diferenciadas, una para residentes y otra para visitantes, con capacidad para más de cinco vehículos, aportando comodidad y discreción.\n\nEl jardín, totalmente llano, con piscina y diversas zonas de relax, convierte esta vivienda en un auténtico oasis urbano, perfecto para quienes desean disfrutar del exterior sin renunciar a la cercanía del centro de la ciudad.\n\nUbicación:\n\nSituada en Avenida Pearson, considerada la calle más exclusiva de Barcelona, la casa se encuentra a pocos minutos de los mejores colegios internacionales (St. Paul’s, St. Peter’s, Liceo Francés), de las escuelas de negocio de referencia como IESE y ESADE, así como de clubes deportivos, zonas verdes y jardines emblemáticos.\n\nNo te pierdas esta oportunidad ¡Ven a verlo! Honorarios de la agencia y gastos de compraventa no están incluidos en el precio.",
    "features": [],
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/cover_xx2gpc",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/1.fachada_gstuc7",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/2.fachada_mgqr78",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/3.salon_hediuy",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/4.salon_izlud7",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/5.salon_mr07er",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/6.salon_xtwdtv",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/7.salon_rtmgvk",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/8.pasillo_oqws7u",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/9.pasillo_f1xivi",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/10.lavado_x3x5ou",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/11.lavado_ffoksl",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/12.habitacion_utfgig",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/13.habitacion_bu6ckq",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/14.habitacion_dawji3",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/15.habitacion_fzsqyw",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/16.habitacion_nkbodh",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/17.balcon_jgalir",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/18.lavado_s45rgc",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/19.lavado_cnttfx",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/20.balcon_djwlmt",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/21.balcon_vgwhlo",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/22.zona_exterior_il39im",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/23.zona_exterior_thvwgh",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/24.vista_mnywzz"
    ],
    "coords": {
      "lat": 41.391,
      "lng": 2.113
    },
    "status": "EN VENTA",
    "dateAdded": "2026-02-06"
  },
  {
    "id": 17,
    "city": "Esplugues de Llobregat",
    "zone": "Can Vidalet",
    "title": "Garaje en venta en Calle del Moli - Can Vidalet - Esplugues de Llobregat",
    "beds": 0,
    "baths": 0,
    "m2": 0,
    "price": 15000,
    "priceLabel": "15.000 €",
    "mode": "compra",
    "category": "parking",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/cover_q0wy9u",
    "desc": "Group Casas presenta en venta DOS PLAZAS de parking, ubicada en Calle Molino, de Esplugues de Llobregat (zona metro Can Vidalet). Situada en Planta -2. Vigilancia 24h con personal de seguridad. Acceso con mando y llave. No te pierdas esta gran oportunidad. ¡Ven a verlo! Honorarios de la agencia y gastos de compra venta no están incluidos en el precio.",
    "features": [],
    "tag": "REBAJADO",
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/cover_q0wy9u",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/1.parking_yvpzgm",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/2.parking_ajzz2y"
    ],
    "coords": {
      "lat": 41.374,
      "lng": 2.088
    },
    "status": "EN VENTA",
    "dateAdded": "2025-12-01"
  },
  {
    "id": 23,
    "city": "Hospitalet de Llobregat",
    "zone": "Santa Eulalia",
    "title": "Piso en Santa Eulalia, Hospitallet de Llobregat",
    "beds": 3,
    "baths": 1,
    "m2": 70,
    "price": 275000,
    "priceLabel": "275.000 €",
    "mode": "compra",
    "category": "piso",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/ChatGPT_Image_13_jul_2026_13_45_10_Copy1_eyacx4",
    "desc": "Group Casas presenta en exclusiva este piso totalmente reformado en venta en Hospitalet de Llobregat, ubicado en la zona de Santa Eulalia. A escasos minutos de las líneas L10S y muy cerca del centro comercial la Gran vía 2, y rodeado de todos los servicios necesarios para el día a día: centros educativos, supermercados, comercios de proximidad y agradables zonas verdes.\nLa vivienda dispone de una superficie aproximada de 70 m?, actualmente distribuida en salón comedor, cocina independiente, tres habitaciones, un baño completo y galería.\nEl inmueble se encuentra totalmente reformado, todo nuevo a estrenar, listo para entrar a vivir.\nAdemás, cuenta con aire acondicionado, electrodomésticos: horno, lavavajillas, nevera.\nDestaca especialmente su impresionante techo de volta catalana original, cuidadosamente restaurado, que aporta personalidad, caracter y un estilo único.\nEs una finca sin ascensor.\nNo te pierdas esta oportunidad.\n¡Ven a verlo! Honorarios de la agencia y gastos de compraventa no están incluidos en el precio.",
    "features": [],
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/ChatGPT_Image_13_jul_2026_13_45_10_Copy1_eyacx4",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/ChatGPT_Image_13_jul_2026_16_09_40_Copy1_apex76",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/ChatGPT_Image_13_jul_2026_13_50_01_Copy1_txzg3r",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/ChatGPT_Image_13_jul_2026_16_08_07_Copy1_basnxj",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/ChatGPT_Image_13_jul_2026_13_57_32_Copy1_ksurum",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/ChatGPT_Image_13_jul_2026_16_08_50_l2a0ot",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/ChatGPT_Image_13_jul_2026_16_09_03_hyzkub"
    ],
    "floor": "2",
    "coords": {
      "lat": 41.365,
      "lng": 2.128
    }
  },
  {
    "id": 26,
    "city": "Esplugues de Llobregat",
    "zone": "Can vidalet",
    "title": "Piso en Can Vidalet",
    "beds": 3,
    "baths": 1,
    "m2": 85,
    "price": 270000,
    "priceLabel": "270.000 €",
    "mode": "compra",
    "category": "piso",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/cover_lstqqj",
    "desc": "Group Casas presenta este espectacular piso en la zona de Can Vidalet (Esplugues de Llobregat), a tan solo diez minutos del centro comercial Finestrelles y del tranvía, este encantador piso ofrece una ubicación inmejorable. Rodeado de escuelas, supermercados a tan solo cinco minutos del metro de Can Vidalet (L5) y a cinco minutos del metro de Can Serra (L1).\nLa vivienda cuenta con 85 m' muy bien distribuidos. Dispone de un amplio y luminoso salón-comedor con salida a una acogedora terraza, una cocina independiente y funcional con acceso a una amplia galería, tres habitaciones amplias (dos de ellas dobles y una individual con altillo), además de un aseo y un baño completo y moderno.\nLa terraza incluye también un práctico trastero.\nNo te pierdas esta oportunidad. ¡Ven a verlo! Los honorarios de la agencia intermediadora y los gastos de compra-venta no están incluidos en el precio.",
    "features": [
      "Ascensor",
      "Terraza",
      "Trastero"
    ],
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/cover_lstqqj",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/01-salon_a0ygco",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/02-salon_p5y0dx",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/03-salon_wolxcv",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/04-terraza_xkfdp6",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/05-terraza_hnnr4b",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/06-habitacion_upc8aq",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/07-habitacion_mi4sum",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/08-habitacio.n_rwmn53",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/09-habitacion_2_yamrgg",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/10-habitacion_rth8gb",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/11-cocina_tjprtt",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/12-cocina_uh5goi",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/13-galeria_yvbe9g",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/14-baño_vbarcq",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/15-baño_qlnugr"
    ],
    "floor": "Entreplanta interior",
    "coords": {
      "lat": 41.375,
      "lng": 2.088
    }
  },
  {
    "id": 27,
    "city": "Hospitalet de Llobregat",
    "zone": "Pubilla Cases, Can Serra",
    "title": "Piso en venta en Pubilla Cases",
    "beds": 1,
    "baths": 1,
    "m2": 55,
    "price": 155000,
    "priceLabel": "155.000 €",
    "mode": "compra",
    "category": "piso",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/cover_mifkzq",
    "desc": "Group Casas presenta en este piso en venta en Hospitalet de Llobregat, ubicado en la zona de Pubilla Casas. A escasos minutos de las líneas L5 y L1 de metro, y rodeado de todos los servicios necesarios para el día a día: centros educativos, supermercados, comercios de proximidad y agradables zonas verdes.\nLa vivienda dispone de una superficie aproximada de 55m?, actualmente distribuida en salón comedor, cocina independiente, una habitacion (con posibilidad de hacer dos), un baño completo y galería.\nEl inmueble se encuentra en buen estado de conservación. Es una finca sin ascensor.\nActualmente alquilado hasta julio del 2027.\nNo te pierdas esta oportunidad.\n¡Ven a verlo!\nHonorarios de la agencia y gastos de compraventa no están incluidos en el precio.",
    "features": [],
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/cover_mifkzq",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/01-salon_ngfskx",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/02-salon_plqqe7",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/03-habitacion_oqucms",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/04-cocina_nzjsgi",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/05-cocina_rhb7zq",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/06-cocina_kzhqyr",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/07-baño_slwfjr",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/08-baño_uwfh12"
    ],
    "floor": "4",
    "coords": {
      "lat": 41.371,
      "lng": 2.101
    }
  },
  {
    "id": 28,
    "city": "Hospitalet de Llobregat",
    "zone": "Pubilla Cases, Can Serra",
    "title": "Piso en venta en Pubilla Cases",
    "beds": 3,
    "baths": 1,
    "m2": 70,
    "price": 179000,
    "priceLabel": "179.000 €",
    "mode": "compra",
    "category": "piso",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/cover_gcsa0o",
    "desc": "Group Casas presenta piso en venta en la zona de Pubilla Casas. A escasos minutos de las líneas L5 y L1 de metro, y rodeado de todos los servicios necesarios para el día a día: centros educativos, supermercados, comercios de proximidad y agradables zonas verdes. 5 minutos hasta llegar al centro comercial Finestrelles.\nLa vivienda dispone de una superficie aproximada de 70m?, actualmente distribuida en salón comedor exterior, amplia cocina independiente, tres habitaciones dobles y un baño completo.\nEl inmueble se encuentra en buen estado pero requiere de algunas reformas. Es una finca SIN ascensor.\n//Las imágenes mostradas son una propuesta visual de cómo podría verse la vivienda vacia. La estructura, distribución y espacios del piso se mantienen exactamente iguales. //.\nNo te pierdas esta oportunidad.\n¡Ven a verlo!\nHonorarios de la agencia y gastos de compraventa no están incluidos en el precio.",
    "features": [],
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/cover_gcsa0o",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/01-salon_zfge13",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/02-habitacion_pfvpqe",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/03-habitacion_rmstm0",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/04-habitacion_qvxhmj",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/05-cocina_cb8fgu",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/06-galeria_ojwccn",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/07-baño_nski06"
    ],
    "floor": "3",
    "coords": {
      "lat": 41.366,
      "lng": 2.1
    }
  },
  {
    "id": 29,
    "city": "Hospitalet de Llobregat",
    "zone": "Santa Eulàlia",
    "title": "Piso en venta en Santa Eulalia",
    "beds": 3,
    "baths": 1,
    "m2": 60,
    "price": 199900,
    "priceLabel": "199.900 €",
    "mode": "compra",
    "category": "piso",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/cover_dkqdkv",
    "desc": "Group Casas presenta este piso ubicado en una zona muy bien comunicada de Santa Eulàlia, cerca de metro L1, autobuses y acceso rápido a las principales vías que conectan con Barcelona y alrededores. Las paradas Torrassa L1 y Can Tries | Gornal L9S-L10S se encuentran a pocos minutos caminando. La zona cuenta con centro de salud, farmacias, supermercados, institutos y todos los servicios básicos.\n\nLa vivienda cuenta con una superficie aproximada de 60 m² y ofrece una distribución funcional compuesta por un luminoso salón-comedor exterior, cocina independiente, tres habitaciones dobles y un baño.\n\nLa finca no dispone de ascensor.\n\nNo te pierdas esta oportunidad.\n¡Ven a verlo! Honorarios de la agencia y gastos de compraventa no están incluidos en el precio.",
    "features": [],
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/cover_dkqdkv",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/01-salon_nl1fyr",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/02-salon_wrbxgq",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/03-cocina_iq5ieq",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/04-habitacion_rscjzj",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/05-habitacion_alshtl",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/06-baño_x4wwyo"
    ],
    "floor": "1",
    "coords": {
      "lat": 41.365,
      "lng": 2.119
    },
    "dateAdded": "2026-07-28"
  },
  {
    "id": 30,
    "city": "Hospitalet de Llobregat",
    "zone": "Santa Eulàlia",
    "title": "Piso en venta en Santa Eulàlia",
    "beds": 3,
    "baths": 1,
    "m2": 70,
    "price": 190000,
    "priceLabel": "190.000 €",
    "mode": "compra",
    "category": "piso",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/cover_vbls8d",
    "desc": "Group Casas presenta este piso ubicado en una zona muy bien comunicada de Santa Eulàlia, cerca de metro L1, autobuses y acceso rápido a las principales vías que conectan con Barcelona y alrededores. Las paradas Torrassa L1 y Can Tries | Gornal L9S-L10S se encuentran a pocos minutos caminando. La zona cuenta con centro de salud, farmacias, supermercados, institutos y todos los servicios básicos.\n\nLa vivienda dispone de una superficie aproximada de 70m², actualmente distribuida en salón comedor con salida a un balcón, cocina independiente, tres habitaciones (una de ella también con salida al balcón) y un baño.\n\nLa finca dispone de ascensor.\nNo te pierdas esta oportunidad.\n¡Ven a verlo! Honorarios de la agencia y gastos de compraventa no están incluidos en el precio.",
    "features": [
      "Ascensor",
      "Terraza"
    ],
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/cover_vbls8d",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/1.balcon_xvzshn",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/2.balcon_hh8qky",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/3.balcon_h6fxau",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/4.habitacion_csi5zm",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/5.habitacion_ni2mc7",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/6.cocina_kcbzrw",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/7.zona_lavado_o6epam",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/8.lavado_ivjitk"
    ],
    "floor": "5",
    "coords": {
      "lat": 41.365,
      "lng": 2.119
    },
    "dateAdded": "2026-07-28"
  },
  {
    "id": 31,
    "city": "Hospitalet de Llobregat",
    "zone": "Pubilla Cases",
    "title": "Piso en venta en Pubilla Cases",
    "beds": 3,
    "baths": 1,
    "m2": 80,
    "price": 249000,
    "priceLabel": "249.000 €",
    "mode": "compra",
    "category": "piso",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/cover_i7daie",
    "desc": "Group Casas presenta piso en venta en Hospitalet de Llobregat, ubicado en la demandada zona de Can Serra. A escasos minutos de las líneas L1 y L5 de metro, y rodeado de todos los servicios necesarios para el día a día: centros educativos, supermercados, comercios de proximidad y agradables zonas verdes.\n\nLa vivienda dispone de una superficie aproximada de 80 m², actualmente distribuida en salón comedor, tres habitaciones dobles, una de ellas con salida al balcón, amplia cocina con salida a una galeria y un baño completo.\n\nEl inmueble se encuentra en buen estado de conservación, listo para entrar a vivir. Es una finca SIN ascensor.\n\nNo te pierdas esta oportunidad.\n¡Ven a verlo!\nHonorarios de la agencia y gastos de compraventa no están incluidos en el precio.",
    "features": [],
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/cover_i7daie",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/1_habitacion_esljve",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/2_balcon_tzahrv",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/3_balcon_mbqskm",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/4_habitacion_hchr6o",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/5_habitacion_gacmxg",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/6_habitacion_izqskb",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/7_habitacion_v9j3qv",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/8_habitacion_icazaa",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/9_habitacion_o7dpc6",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/10_habitacion_zl1prg",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/11_habitacion_mgsszs",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/12_salon_xpwvqo",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/13_salon_o8w41g",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/14_salon_pvsf5p",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/15_salon_cek5oi",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/16_baño_jh76tu",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/17_baño_ppl0tg"
    ],
    "floor": "2",
    "coords": {
      "lat": 41.366,
      "lng": 2.1
    },
    "dateAdded": "2026-08-26"
  },
  {
    "id": 32,
    "city": "Hospitalet de Llobregat",
    "zone": "Santa Eulàlia",
    "title": "Piso en venta en Santa Eulàlia",
    "beds": 3,
    "baths": 1,
    "m2": 70,
    "price": 290000,
    "priceLabel": "290.000 €",
    "mode": "compra",
    "category": "piso",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/cover_dogl4c",
    "desc": "Group Casas presenta piso en venta en L’Hospitalet de Llobregat, situado en el acogedor barrio de Santa Eulàlia. A escasos minutos de la estación de metro Santa Eulàlia, línea L1, y rodeado de todos los servicios necesarios para el día a día: centros educativos, supermercados, comercios de proximidad, mercados y zonas verdes.\n\nLa vivienda, totalmente reformada, dispone de tres habitaciones y estancias exteriores que proporcionan una agradable entrada de luz natural.\n\nEl inmueble se encuentra en una planta entresuelo de una finca con ascensor. Gracias a su excelente estado de conservación, está listo para entrar a vivir.\n\nNo te pierdas esta oportunidad.\n¡Ven a verlo!\n\nHonorarios de la agencia y gastos de compraventa no incluidos en el precio.",
    "features": [
      "Ascensor"
    ],
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/cover_dogl4c",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/1_salon_j7onsf",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/2_salon_xh1mmz",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/3_salon_htakff",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/4_salon_uuakmm",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/5_salon_ycvd6b",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/6_habitación_rd81b2",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/7_habitación_ztye8h",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/8_habitación_vnty0u",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/9_habitación_k11hdr",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/10_cocina_rdlz6s",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/11_cocina_plfztu",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/12_ropas_nquqjs",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/13_ropas_hijanb",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/14_baño_nt1hir",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/15_baño_ocdkob"
    ],
    "floor": "Entreplanta",
    "coords": {
      "lat": 41.362,
      "lng": 2.125
    },
    "dateAdded": "2026-09-07"
  },
  {
    "id": 33,
    "city": "Esplugues de Llobregat",
    "zone": "Can Vidalet",
    "title": "Piso en venta en Can Vidalet",
    "beds": 3,
    "baths": 1,
    "m2": 92,
    "price": 235000,
    "priceLabel": "235.000 €",
    "mode": "compra",
    "category": "piso",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/cover_u7esnk",
    "desc": "Group Casas presenta piso en venta en Esplugues de Llobregat, situado en el acogedor entorno de Can Vidalet. A escasos minutos de la línea L5 de metro y rodeado de todos los servicios necesarios para el día a día: centros educativos, mercados, comercios y supermercados. Además, cuenta con fácil acceso a la Ronda de Dalt y se encuentra a pocos minutos del Centro Comercial Finestrelles.\n\nLa vivienda dispone de una superficie aproximada de 92 m², actualmente distribuida en un amplio salón comedor de 22 m² con salida al balcón, tres habitaciones dobles —anteriormente cuatro—, gran cocina office de 12 m² con acceso a una galería, recibidor, pasillo distribuidor y un baño completo con plato de ducha.\n\nSe encuentra en una tercera planta interior de una finca con ascensor, renovada y con la Inspección Técnica del Edificio (ITE) superada.\n\nLa vivienda se encuentra actualmente alquilada. Consultar condiciones.\n\nNo te pierdas esta oportunidad.\n¡Ven a verlo!\n\nHonorarios de la agencia y gastos de compraventa no incluidos en el precio.",
    "features": [
      "Ascensor",
      "Balcón"
    ],
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/cover_u7esnk",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/1.salon_hrrymn",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/2.salon_pcyopa",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/3.salon_cpygfz",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/4.balcon_sb1ugg",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/5.balcon_opfa2j",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/6.habitacion_aoarik",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/7.habitación_dx3vn3",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/8.habitacion_uoogwb",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/9.habitacion_vw0dpj",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/10.habitacion_rwzh4u",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/11.habitacion_x1pftm",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/12.cocina_eoovbf",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/13.cocina_bhfp5k",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/14.cocina_bi9s2f",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/15.zona_lavado_l1jqil",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/16.zona_lavado_yzzbuw",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/17.lavado_tftw00",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/18.lavado_qnbxpc"
    ],
    "floor": "3",
    "coords": {
      "lat": 41.37,
      "lng": 2.098
    },
    "dateAdded": "2026-09-07"
  },
  {
    "id": 34,
    "city": "Barcelona",
    "zone": "Vallirana",
    "title": "Piso en venta en Vallirana",
    "beds": 3,
    "baths": 2,
    "m2": 352,
    "price": 459000,
    "priceLabel": "459.000 €",
    "mode": "compra",
    "category": "piso",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/cover_bweiea",
    "desc": "Group Casas presenta en exclusiva esta magnífica vivienda unifamiliar situada en la urbanización El Lledoner de Vallirana, una zona residencial tranquila y rodeada de naturaleza, ideal para quienes buscan amplitud, privacidad y calidad de vida a poca distancia de Barcelona.\n\nLa propiedad cuenta con 352 m² construidos sobre una parcela de 1.067 m², con amplios espacios interiores y exteriores pensados para disfrutar en familia durante todo el año.\n\nDistribución:\n\nEn la planta baja encontramos un amplio garaje con capacidad para varios vehículos, junto a una espaciosa zona de bodega multifuncional que ofrece numerosas posibilidades como sala de ocio, gimnasio, despacho, estudio o zona independiente. Esta planta dispone además de un baño completo.\n\nLa planta principal alberga un luminoso salón-comedor con chimenea, grandes ventanales y acceso directo a una fantástica terraza con agradables vistas despejadas a la montaña.\n\nLa cocina es amplia, funcional y disfruta de abundante luz natural. La zona de noche se distribuye en tres dormitorios, dos dobles y uno individual, además de un espacioso baño completo de cuatro piezas.\n\nExteriores:\n\nLa vivienda dispone de un agradable jardín delantero con árboles frutales y una amplia zona de acceso con espacio para estacionar varios vehículos adicionales.\n\nEn la parte posterior encontramos una zona de barbacoa de obra, piscina elevada, área de césped artificial y almacén auxiliar, creando un espacio perfecto para disfrutar de reuniones familiares y momentos al aire libre.\n\nEntre sus calidades destacan los suelos de gres, ventanas de aluminio con doble acristalamiento Climalit, calefacción mediante radiadores, puerta de seguridad y chimenea.\n\nUbicación:\n\nSituada en la consolidada urbanización El Lledoner de Vallirana, la propiedad disfruta de un entorno natural privilegiado y buenas comunicaciones, con rápido acceso a la B-24, facilitando la conexión con Barcelona, el aeropuerto y las principales vías de comunicación.\n\nUna excelente oportunidad para quienes buscan una casa amplia, independiente y rodeada de naturaleza, sin renunciar a la proximidad de la ciudad.\n\nDeterminadas imágenes pueden contener recreaciones virtuales o representaciones digitales de carácter meramente orientativo y no contractual.\n\nNo te pierdas esta oportunidad.\n¡Ven a verlo!\n\nHonorarios de la agencia y gastos de compraventa no incluidos en el precio.",
    "features": [
      "Terraza",
      "Jardín privado",
      "Garaje"
    ],
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/cover_bweiea",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/1_salon_k3pjsj",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/2_balcon_m2edri",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/3_chimenea_me38ux",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/4_cocina_umb8y2",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/5_habitación_bbs8jr",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/6_habitacion_xu37j3",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/7_habitación_a3fnht",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/8_habitaión_gztdae",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/9_habitación_u3ak9z",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/10_baño_mlezfx",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/11_garaje_yvdkz2",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/12_garaje_fyk2mu",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/13_garaje_eznpfe",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/14_garaje_nlr7in",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/15_zona_exterior_a6v3du",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/16_zona_exterior_y3d8ak",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/17_piscina_mb2v5t",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/18_piscina_q1htju"
    ],
    "coords": {
      "lat": 41.386,
      "lng": 1.883
    },
    "dateAdded": "2026-09-07"
  },
  {
    "id": 35,
    "city": "Hospitalet de Llobregat",
    "zone": "Pubilla Cases, Can Serra",
    "title": "Piso en venta en Pubilla Cases",
    "beds": 3,
    "baths": 1,
    "m2": 88,
    "price": 235000,
    "priceLabel": "235.000 €",
    "mode": "compra",
    "category": "piso",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/2_salon_tymjrz",
    "desc": "Group Casas presenta piso en venta en Hospitalet de Llobregat, ubicado en el acogedor entorno de Pubilla Cases. A escasos minutos de las líneas L1 y L5 de metro, y rodeado de todos los servicios necesarios para el día a día: centros educativos, supermercados, comercios de proximidad y agradables zonas verdes.\n\nLa vivienda dispone de una superficie aproximada de 88 m², actualmente distribuida en salón comedor, tres habitaciones dobles, una de ellas con salida al balcón, amplia cocina con salida a una galeria y un baño completo.\n\nEl inmueble se encuentra en buen estado de conservación, listo para entrar a vivir. Es una finca SIN ascensor.\n\nNo te pierdas esta oportunidad.\n¡Ven a verlo!\nHonorarios de la agencia y gastos de compraventa no están incluidos en el precio.",
    "features": [
      "Balcón"
    ],
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/2_salon_tymjrz",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/3_balcon_wnpb2s",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/4_salon_cpxkp5",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/5_habitación_axbcgc",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/6_habitación_rc7ik4",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/7_habitación_f4p3ud"
    ],
    "floor": "2",
    "coords": {
      "lat": 41.369,
      "lng": 2.101
    },
    "dateAdded": "2026-09-07"
  },
  {
    "id": 36,
    "city": "Esplugues de Llobregat",
    "zone": "La Plana - Montesa",
    "title": "Traspaso de negocio con inmueble en alquiler en La Plana - Montesa",
    "beds": 6,
    "baths": 3,
    "m2": 465,
    "price": 45000,
    "priceLabel": "45.000 €",
    "mode": "compra",
    "category": "local",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/cover_gzcglx",
    "desc": "Group Casas presenta traspaso de negocio y alquiler de amplio local comercial a pie de calle en La Plana – Montesa, Esplugues de Llobregat\n\nEn una ubicación estratégica y de gran actividad en Esplugues de Llobregat, se ofrece en traspaso por 45.000 € y alquiler mensual de 1.600 € este magnífico local comercial de 465 m² construidos, situado íntegramente en planta baja y a pie de calle, lo que garantiza máxima visibilidad y un cómodo acceso para tus clientes.\n\nEl inmueble se encuentra en buen estado de conservación y destaca por su amplitud y versatilidad. Cuenta con una superficie construida de 465 m² distribuida de forma funcional en 6 estancias y 3 baños. Sus espacios luminosos y bien estructurados ofrecen una excelente oportunidad para continuar o emprender un proyecto comercial con un espacio listo para trabajar.\n\nLa Plana - Montesa es un barrio dinámico en constante crecimiento, rodeado de comercio local, oficinas y una consolidada zona residencial. Su entorno ofrece una amplia oferta de servicios y equipamientos, garantizando un flujo constante de público y clientes potenciales durante todo el día.\n\nLa zona destaca por sus excelentes comunicaciones: rápido acceso en coche a la Ronda de Dalt, la A-2 y la B-23, así como conexión directa con Barcelona y el aeropuerto. Además, dispone de gran proximidad al transporte público, con la red de tranvía (Trambaix) y varias líneas de autobús.\n\nCondiciones económicas:\n\nTraspaso: 45.000 €\n\nAlquiler: 1.600 € / mes\n\nNo te pierdas esta oportunidad para arrancar tu negocio en una ubicación inmejorable.\n¡Ven a verlo!\n\nHonorarios de la agencia y gastos de la operación no están incluidos en el precio.",
    "features": [
      "Aire acondicionado"
    ],
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/cover_gzcglx",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/1_local_zztjvm",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/2_local_okjceo",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/3_local_xsbnvy",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/4_local_qcia0x",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/5_local_yjyrag",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/6_local_lilqt9",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/7_local_oqsbl2",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/8_plano_ivnt9p"
    ],
    "coords": {
      "lat": 41.372,
      "lng": 2.086
    },
    "dateAdded": "2026-09-07"
  },
  {
    "id": 37,
    "city": "Hospitalet de Llobregat",
    "zone": "Sanfeliu, Centre",
    "title": "Piso en venta en Sanfeliu",
    "beds": 4,
    "baths": 1,
    "m2": 86,
    "price": 272000,
    "priceLabel": "272.000 €",
    "mode": "compra",
    "category": "piso",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/1_salon_ift4o2",
    "desc": "Group Casas presenta piso en venta en Can Boixeres - L’Hospitalet de Llobregat, se encuentra rodeada de comercios, supermercados, transporte público y todos los servicios necesarios para el día a día. La proximidad al metro Can Boixeres -L5- permite desplazarse cómodamente hacia Barcelona y otros puntos de L'Hospitalet.\n\nLa vivienda cuenta con una superficie de 86 m² que se distribuyen en una amplia salon comedor con salida a un balcón exterior y cuenta con 4 habitaciones, una de ellas con salida al balcón, amplia cocina con galería, ofreciendo diferentes posibilidades para adaptarse a las necesidades de cada familia.\n\nEl piso es exterior y dispone de dos balcones, que aportan luz natural y un agradable espacio exterior a la vivienda.\n\nEl inmueble se encuentra en buen estado de conservación, listo para entrar a vivir. Es una finca SIN ascensor.\n\nNo te pierdas esta oportunidad.\n¡Ven a verlo!\n\nHonorarios de la agencia y gastos de compraventa no están incluidos en el precio.",
    "features": [
      "Balcón",
      "Aire acondicionado"
    ],
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/1_salon_ift4o2",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/2_balcon_nxgwjh",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/3_salon_zpn4s6",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/4_salon_dwrxzq",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/5_pasillo_kma0we",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/6_pasillo_kdeaao",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/7_cocina_n2j5jl",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/8_cocina_yse9zw",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/9_ropas_knqyox",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/10_ropas_ni4qws",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/11_habitación_hfngsp",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/12_habitacion_zmyjjg",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/13_habitacion_juyoa4",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/14_habitacion_t3vxqw",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/15_habitacion_w8hfzd",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/16_habitacion_r2kuih",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/17_estudio_p7nsvy",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/17_habitacion_ckltb2",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/18_baño_due2xw"
    ],
    "floor": "2",
    "coords": {
      "lat": 41.366,
      "lng": 2.087
    },
    "dateAdded": "2026-09-07"
  },
  {
    "id": 38,
    "city": "Esplugues de Llobregat",
    "zone": "La Plana - Montesa",
    "title": "Piso en venta en La Plana - Montesa",
    "beds": 4,
    "baths": 2,
    "m2": 110,
    "price": 395000,
    "priceLabel": "395.000 €",
    "mode": "compra",
    "category": "piso",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/cover_bnzzam",
    "desc": "Group Casas presenta luminoso piso exterior con terraza en venta, situado en La Montesa, una de las zonas más tranquilas y demandadas de Esplugues de Llobregat.\n\nLa vivienda dispone de una superficie aproximada de 110 m², distribuida en un amplio salón comedor con salida al balcón, cocina independiente, galería ideal como zona de lavandería o almacenaje, cuatro amplias habitaciones —una de ellas en suite con baño privado— y un segundo baño completo.\n\nEl inmueble destaca por su luminosidad, amplitud y excelente distribución. Además, cuenta con una soleada terraza, perfecta para disfrutar del aire libre y crear una agradable zona de descanso.\n\nSe encuentra en una finca con ascensor, ubicada en un entorno privilegiado y rodeada de todos los servicios necesarios para el día a día: centros educativos, supermercados, comercios de proximidad, zonas verdes y transporte público. Asimismo, dispone de buenas comunicaciones con Barcelona y con los principales accesos viarios.\n\nNo te pierdas esta oportunidad.\n¡Ven a verlo!\n\nHonorarios de la agencia y gastos de compraventa no incluidos en el precio.",
    "features": [
      "Ascensor",
      "Terraza",
      "Balcón"
    ],
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/cover_bnzzam",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/1_sala_gtkizw",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/2_balcon_ztw4c2",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/3_sala_t2krv7",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/4_sala_kd3olx",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/5_sala_znijro",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/6_sala_to1fob",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/7_habitacion_uwoomp",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/8_habitacion_pb6v3v",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/9_habitacion_sp90hy",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/10_habitacion_ss043o",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/11_habitacion_qmdhbm",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/12_habitacion_oxtgpb",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/13_habitacion_lnulzt",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/14_habitacion_gumcai",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/15_habitacion_wtbuxq",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/16_habitacion_axv07d",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/17_habitacion_zbmmqa",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/18_baño_j6fyfd",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/19_baño_es7izl",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/20_daño_fl1tjt",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/21_baño_i47sx1",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/22_cocina_uwtr4w",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/23_cocina_y5p6us",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/24_cocina_emamne",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/25_ropas_s3lqen",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/26_cocina_och1os",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/26_habitacion_r6gfww",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/27_cocina_apc5uo",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/27_habitacion_oefzff",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/28_habitacion_dquub0",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/29_almacen_sh1sik",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/30_almacen_epymdf",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/31baño_sqiglw",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/32_baño_kyf1ij",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/33_baño_sdbfgo",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/34_terraza_njiogg",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/35_terraza_lkeymd",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/36_terraza_k5pyjo",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/37_teraza_m89mcy",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/38_terraza_dftsbb"
    ],
    "floor": "4",
    "coords": {
      "lat": 41.373,
      "lng": 2.088
    },
    "dateAdded": "2026-09-09"
  },
  {
    "id": 39,
    "city": "Esplugues de Llobregat",
    "zone": "Can Vidalet",
    "title": "Piso en venta en Can Vidalet",
    "beds": 2,
    "baths": 1,
    "m2": 45,
    "price": 155000,
    "priceLabel": "155.000 €",
    "mode": "compra",
    "category": "piso",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/cover_srmrck",
    "desc": "Group Casas presenta piso en venta en Esplugues de Llobregat, ubicado en la zona de Can Vidalet. A escasos minutos de las líneas L5 y L1 de metro, y rodeado de todos los servicios necesarios para el día a día: centros educativos, supermercados, comercios de proximidad y agradables zonas verdes.\n\nLa vivienda dispone de una superficie aproximada de 45m², actualmente distribuida en salón comedor, dos habitaciones (dos dobles), amplia cocina y un baño completo. También dispone de aire acondicionado en la vivienda.\n\nEl inmueble se encuentra en buen estado de conservación, listo para entrar a vivir. Es una finca SIN ascensor. Actualmente la vivienda se encuentra alquilada. \n\n//Las imágenes mostradas son una propuesta visual de cómo podría verse la vivienda sin muebles. La estructura, distribución y espacios del piso se mantienen exactamente iguales. //\n\nNo te pierdas esta oportunidad.\n¡Ven a verlo!\nHonorarios de la agencia y gastos de compraventa no están incluidos en el precio.",
    "features": [],
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/cover_srmrck",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/1_habitacion_mxc2rh",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/2_habitacion_zvrxsv",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/3_habitacion_okol58",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/4_habitacion_rfkyov",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/5_salon_bxx9mj",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/6_salon_vhslx5",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/7_cocina_zyfee1",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/8_baño_a8kpra",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/9_baño_qvoxwm"
    ],
    "floor": "3",
    "coords": {
      "lat": 41.372,
      "lng": 2.098
    },
    "dateAdded": "2026-09-09"
  },
  {
    "id": 40,
    "city": "Hospitalet de Llobregat",
    "zone": "La Florida, La Florida - Les Planes",
    "title": "Piso en venta en La Florida, La Florida - Les Planes",
    "beds": 3,
    "baths": 1,
    "m2": 66,
    "price": 249000,
    "priceLabel": "249.000 €",
    "mode": "compra",
    "category": "piso",
    "image": "https://res.cloudinary.com/clkttf37/image/upload/c_fill,ar_4:3,w_900,f_auto,q_auto/cover_oxo8ui",
    "desc": "Group Casas presenta piso totalmente reformado en venta en Hospitalet de Llobregat en la zona de La Florida. Este hogar luminoso y acogedor está perfectamente ubicado, a solo 5 minutos de la estación de metro L1 (Florida) y a 10 minutos de la L5 (Pubillas Casas)\n\nRodeado de supermercados, amplias zonas verdes y una variada oferta de bares y restaurantes, este piso es ideal para disfrutar de la vida urbana al máximo.\n\nCon una superficie aproximada de 66m², el inmueble cuenta con un amplio salón-comedor, una amplia cocina, tres habitaciones, dos dobles y una individual, además de un baño completo de doble pica totalmente reformado. La finca también dispone de ascensor para mayor comodidad.\n\nPiso totalmente reformado con materiales inverter con bomba de calor, aluminio climalit oscilobatiente, suelos y alicatados porcelanico. Encimera Dekton, horno, microondas bosch, lavavajillas, combi inverter.\n\n¡No dejes pasar esta increíble oportunidad! ¡Ven a verlo!\n\nLos honorarios de la agencia y los gastos de compraventa no están incluidos en el precio.",
    "features": [
      "Ascensor",
      "Aire acondicionado"
    ],
    "images": [
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/cover_oxo8ui",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/1_salon_gonwv9",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/2_salon_iomqoh",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/3_salon_dburer",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/4_habitacion_gbmavq",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/5_habitacion_dqrglw",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/6_habitacion_jnwafl",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/7_baño_iurmfk",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/8_pasillo_ttgayu",
      "https://res.cloudinary.com/clkttf37/image/upload/c_limit,w_1600,f_auto,q_auto/9_entrada_ajzooa"
    ],
    "floor": "2",
    "coords": {
      "lat": 41.369,
      "lng": 2.109
    },
    "dateAdded": "2026-09-09"
  }
]
