import type { Property, MapPin } from './types'

export const homeFeaturedProperties: Property[] = [
  {
    id: 101,
    city: 'Barcelona',
    zone: 'Esplugues',
    title: 'Piso reformado con terraza',
    beds: 3,
    baths: 2,
    m2: 95,
    price: 285000,
    priceLabel: '285.000 €',
    mode: 'compra',
    category: 'piso',
    tag: 'Nuevo',
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80',
    desc: 'Piso reformado con terraza en una zona residencial muy bien comunicada.',
    features: ['Terraza', 'Reformado', 'Ascensor'],
    coords: { lat: 41.3779, lng: 2.0886 },
  },
  {
    id: 102,
    city: 'Barcelona',
    zone: 'Sant Just Desvern',
    title: 'Casa adosada con jardin',
    beds: 4,
    baths: 2,
    m2: 180,
    price: 520000,
    priceLabel: '520.000 €',
    mode: 'compra',
    category: 'chalet',
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=900&q=80',
    desc: 'Casa adosada con jardin privado y estancias amplias para una vida familiar comoda.',
    features: ['Jardin', 'Garaje', 'Terraza'],
    coords: { lat: 41.3845, lng: 2.0752 },
  },
  {
    id: 103,
    city: 'Barcelona',
    zone: 'Cornella',
    title: 'Atico con vistas panoramicas',
    beds: 2,
    baths: 1,
    m2: 72,
    price: 320000,
    priceLabel: '320.000 €',
    mode: 'compra',
    category: 'piso',
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80',
    desc: 'Atico luminoso con vistas abiertas y una distribucion practica.',
    features: ['Vistas', 'Ascensor', 'Terraza'],
    floor: '5ª',
    coords: { lat: 41.3566, lng: 2.0708 },
  },
  {
    id: 104,
    city: 'Barcelona',
    zone: 'Sant Joan Despi',
    title: 'Duplex con terraza y parking',
    beds: 4,
    baths: 2,
    m2: 130,
    price: 480000,
    priceLabel: '480.000 €',
    mode: 'compra',
    category: 'piso',
    tag: 'Destacado',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80',
    desc: 'Duplex amplio con terraza y plaza de parking incluida.',
    features: ['Terraza', 'Parking', 'Trastero'],
    coords: { lat: 41.3677, lng: 2.0569 },
  },
  {
    id: 105,
    city: 'Barcelona',
    zone: 'Esplugues',
    title: 'Piso luminoso junto al parque',
    beds: 2,
    baths: 1,
    m2: 68,
    price: 245000,
    priceLabel: '245.000 €',
    mode: 'compra',
    category: 'piso',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=900&q=80',
    desc: 'Piso luminoso junto a zonas verdes, ideal como primera vivienda.',
    features: ['Luz natural', 'Balcon', 'Parque cercano'],
    coords: { lat: 41.3715, lng: 2.0835 },
  },
  {
    id: 106,
    city: 'Barcelona',
    zone: 'Sant Feliu de Llobregat',
    title: 'Planta baja con jardin privado',
    beds: 3,
    baths: 2,
    m2: 112,
    price: 390000,
    priceLabel: '390.000 €',
    mode: 'compra',
    category: 'piso',
    tag: 'Nuevo',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=900&q=80',
    desc: 'Planta baja con jardin privado y salida directa desde la zona de dia.',
    features: ['Jardin', 'Planta baja', 'Trastero'],
    coords: { lat: 41.3804, lng: 2.0452 },
  },
  {
    id: 107,
    city: 'Barcelona',
    zone: 'Cornella',
    title: 'Estudio moderno en el centro',
    beds: 1,
    baths: 1,
    m2: 42,
    price: 175000,
    priceLabel: '175.000 €',
    mode: 'compra',
    category: 'piso',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=900&q=80',
    desc: 'Estudio moderno en el centro, bien conectado y listo para entrar.',
    features: ['Reformado', 'Centro', 'Transporte cercano'],
    coords: { lat: 41.3583, lng: 2.0730 },
  },
  {
    id: 108,
    city: 'Barcelona',
    zone: 'Sant Just Desvern',
    title: 'Villa con piscina y vistas',
    beds: 5,
    baths: 3,
    m2: 280,
    price: 980000,
    priceLabel: '980.000 €',
    mode: 'compra',
    category: 'chalet',
    tag: 'Exclusiva',
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=900&q=80',
    desc: 'Villa con piscina, vistas despejadas y espacios exteriores pensados para disfrutar.',
    features: ['Piscina', 'Jardin', 'Garaje', 'Vistas'],
    coords: { lat: 41.3914, lng: 2.0788 },
  },
]

export const properties: Property[] = [
  ...homeFeaturedProperties,
  // ── Eixample ────────────────────────────────────────────────────────────────
  {
    id: 1,
    city: 'Barcelona',
    zone: 'Eixample',
    title: 'Piso reformado luminoso en finca regia',
    beds: 3,
    baths: 2,
    m2: 95,
    price: 385000,
    priceLabel: '385.000 €',
    mode: 'compra',
    category: 'piso',
    tag: 'Destacado',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&h=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&h=800&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=1200&h=800&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&h=800&q=80',
      'https://images.unsplash.com/photo-1600210492493-0946911123ea?auto=format&fit=crop&w=1200&h=800&q=80',
      'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=1200&h=800&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&h=800&q=80',
    ],
    desc: 'Magnífico piso completamente reformado en finca regia. Techos altos, suelos de parquet, cocina equipada.',
    features: ['Ascensor', 'Parquet', 'Cocina equipada', 'Portero'],
    floor: '3ª',
    coords: { lat: 41.3944, lng: 2.1615 },
  },
  {
    id: 8,
    city: 'Barcelona',
    zone: 'Eixample',
    title: 'Piso luminoso en alquiler',
    beds: 2,
    baths: 1,
    m2: 70,
    price: 1400,
    priceLabel: '1.400 €/mes',
    mode: 'alquiler',
    category: 'piso',
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=80',
    desc: 'Piso muy luminoso en el centro del Eixample. Completamente amueblado.',
    features: ['Amueblado', 'Ascensor', 'Portero', 'Aire acondicionado'],
    floor: '3ª',
    coords: { lat: 41.3921, lng: 2.1640 },
  },
  {
    id: 12,
    city: 'Barcelona',
    zone: 'Eixample',
    title: 'Plaza de parking en edificio seguro',
    beds: 0,
    baths: 0,
    m2: 12,
    price: 28000,
    priceLabel: '28.000 €',
    mode: 'compra',
    category: 'parking',
    image: 'https://images.unsplash.com/photo-1590674899484-d5640e854abe?auto=format&fit=crop&w=900&q=80',
    desc: 'Plaza de parking en garaje comunitario con acceso 24h y videovigilancia.',
    features: ['Videovigilancia', '24h', 'Acceso remoto'],
    coords: { lat: 41.3933, lng: 2.1602 },
  },
  {
    id: 21,
    city: 'Barcelona',
    zone: 'Eixample',
    title: 'Piso de diseño en el Eixample Esquerra',
    beds: 3,
    baths: 2,
    m2: 88,
    price: 1650,
    priceLabel: '1.650 €/mes',
    mode: 'alquiler',
    category: 'piso',
    tag: 'Nuevo',
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=900&q=80',
    desc: 'Piso recién reformado con acabados de diseño. Cocina abierta, habitaciones amplias.',
    features: ['Amueblado', 'Ascensor', 'Aire acondicionado', 'Parquet'],
    floor: '4ª',
    coords: { lat: 41.3870, lng: 2.1551 },
  },
  // ── Gràcia ──────────────────────────────────────────────────────────────────
  {
    id: 2,
    city: 'Barcelona',
    zone: 'Gràcia',
    title: 'Ático con terraza privada y vistas',
    beds: 2,
    baths: 1,
    m2: 68,
    price: 295000,
    priceLabel: '295.000 €',
    mode: 'compra',
    category: 'piso',
    tag: 'Nuevo',
    image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=80',
    desc: 'Ático luminoso con terraza de 15m² con vistas a la ciudad. Ideal para parejas.',
    features: ['Terraza', 'Ascensor', 'Armarios empotrados'],
    floor: '5ª',
    coords: { lat: 41.4036, lng: 2.1567 },
  },
  {
    id: 9,
    city: 'Barcelona',
    zone: 'Gràcia',
    title: 'Estudio moderno en alquiler',
    beds: 1,
    baths: 1,
    m2: 38,
    price: 950,
    priceLabel: '950 €/mes',
    mode: 'alquiler',
    category: 'piso',
    tag: 'Nuevo',
    image: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?auto=format&fit=crop&w=900&q=80',
    desc: 'Estudio totalmente renovado a estrenar. Excelentes comunicaciones.',
    features: ['Reformado', 'Amueblado', 'Calefacción'],
    floor: '2ª',
    coords: { lat: 41.4052, lng: 2.1534 },
  },
  // ── Sant Martí ──────────────────────────────────────────────────────────────
  {
    id: 3,
    city: 'Barcelona',
    zone: 'Sant Martí',
    title: 'Piso a estrenar con materiales premium',
    beds: 4,
    baths: 2,
    m2: 110,
    price: 450000,
    priceLabel: '450.000 €',
    mode: 'compra',
    category: 'piso',
    tag: 'Nuevo',
    image: 'https://images.unsplash.com/photo-1616137466211-f939a420be84?auto=format&fit=crop&w=900&q=80',
    desc: 'Obra nueva con materiales de primera calidad. Certificación energética A.',
    features: ['Ascensor', 'Garaje', 'Trastero', 'Domótica'],
    floor: '2ª',
    coords: { lat: 41.4124, lng: 2.1989 },
  },
  {
    id: 11,
    city: 'Barcelona',
    zone: 'Sant Martí',
    title: 'Local comercial diáfano',
    beds: 0,
    baths: 1,
    m2: 85,
    price: 320000,
    priceLabel: '320.000 €',
    mode: 'compra',
    category: 'local',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=900&q=80',
    desc: 'Local en planta baja en zona comercial de alto tránsito. Escaparate a pie de calle.',
    features: ['Planta baja', 'Escaparate', 'Aseo'],
    coords: { lat: 41.4098, lng: 2.2011 },
  },
  // ── Sants ───────────────────────────────────────────────────────────────────
  {
    id: 4,
    city: 'Barcelona',
    zone: 'Sants',
    title: 'Estudio con balcón reformado',
    beds: 1,
    baths: 1,
    m2: 42,
    price: 175000,
    priceLabel: '175.000 €',
    mode: 'compra',
    category: 'piso',
    image: 'https://images.unsplash.com/photo-1536858974309-969bef4eeef6?auto=format&fit=crop&w=900&q=80',
    desc: 'Perfecto como primera vivienda o inversión. Muy bien comunicado.',
    features: ['Balcón', 'Reformado'],
    floor: '1ª',
    coords: { lat: 41.3747, lng: 2.1421 },
  },
  {
    id: 22,
    city: 'Barcelona',
    zone: 'Sants',
    title: 'Piso familiar cerca de la estación',
    beds: 3,
    baths: 2,
    m2: 82,
    price: 1100,
    priceLabel: '1.100 €/mes',
    mode: 'alquiler',
    category: 'piso',
    image: 'https://images.unsplash.com/photo-1630699144867-37acec97df5a?auto=format&fit=crop&w=900&q=80',
    desc: 'Piso amplio y bien comunicado, a 5 minutos de Sants Estació. Ideal para familias.',
    features: ['Ascensor', 'Amueblado', 'Trastero'],
    floor: '2ª',
    coords: { lat: 41.3765, lng: 2.1398 },
  },
  // ── Poble Sec ───────────────────────────────────────────────────────────────
  {
    id: 5,
    city: 'Barcelona',
    zone: 'Poble Sec',
    title: 'Piso con encanto en finca clásica',
    beds: 2,
    baths: 1,
    m2: 65,
    price: 260000,
    priceLabel: '260.000 €',
    mode: 'compra',
    category: 'piso',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80',
    desc: 'Piso con carácter en finca clásica. Techos altos y mucha luz natural.',
    features: ['Techos altos', 'Parquet', 'Balcón'],
    floor: '2ª',
    coords: { lat: 41.3726, lng: 2.1614 },
  },
  // ── Les Corts ───────────────────────────────────────────────────────────────
  {
    id: 6,
    city: 'Barcelona',
    zone: 'Les Corts',
    title: 'Dúplex con parking y trastero',
    beds: 3,
    baths: 2,
    m2: 120,
    price: 510000,
    priceLabel: '510.000 €',
    mode: 'compra',
    category: 'piso',
    tag: 'Exclusiva',
    image: 'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?auto=format&fit=crop&w=900&q=80',
    desc: 'Espectacular dúplex con plaza de parking y trastero incluidos.',
    features: ['Garaje', 'Trastero', 'Ascensor', 'Terraza'],
    floor: '4ª-5ª',
    coords: { lat: 41.3851, lng: 2.1283 },
  },
  // ── Sarrià ──────────────────────────────────────────────────────────────────
  {
    id: 7,
    city: 'Barcelona',
    zone: 'Sarrià',
    title: 'Chalet unifamiliar con jardín',
    beds: 5,
    baths: 3,
    m2: 280,
    price: 1200000,
    priceLabel: '1.200.000 €',
    mode: 'compra',
    category: 'chalet',
    tag: 'Exclusiva',
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=900&q=80',
    desc: 'Impresionante chalet en zona residencial tranquila con jardín y piscina.',
    features: ['Jardín', 'Piscina', 'Garaje', 'Domótica', 'Alarma'],
    coords: { lat: 41.4011, lng: 2.1167 },
  },
  {
    id: 23,
    city: 'Barcelona',
    zone: 'Sarrià',
    title: 'Ático en alquiler con vistas al Tibidabo',
    beds: 3,
    baths: 2,
    m2: 105,
    price: 2200,
    priceLabel: '2.200 €/mes',
    mode: 'alquiler',
    category: 'piso',
    tag: 'Exclusiva',
    image: 'https://images.unsplash.com/photo-1571508601891-ca5e7a713859?auto=format&fit=crop&w=900&q=80',
    desc: 'Ático de lujo con terraza panorámica y vistas al Tibidabo. Zona muy tranquila.',
    features: ['Terraza', 'Amueblado', 'Garaje', 'Aire acondicionado'],
    floor: '6ª',
    coords: { lat: 41.4021, lng: 2.1134 },
  },
  // ── Horta ───────────────────────────────────────────────────────────────────
  {
    id: 10,
    city: 'Barcelona',
    zone: 'Horta',
    title: 'Piso familiar con terraza corrida',
    beds: 4,
    baths: 2,
    m2: 98,
    price: 340000,
    priceLabel: '340.000 €',
    mode: 'compra',
    category: 'piso',
    image: 'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=900&q=80',
    desc: 'Amplio piso familiar con terraza de 20m². Zona tranquila con parques.',
    features: ['Terraza', 'Ascensor', 'Garaje opcional', 'Parquet'],
    floor: '4ª',
    coords: { lat: 41.4267, lng: 2.1683 },
  },
  // ── Barceloneta ─────────────────────────────────────────────────────────────
  {
    id: 13,
    city: 'Barcelona',
    zone: 'Barceloneta',
    title: 'Piso a 50m de la playa',
    beds: 2,
    baths: 1,
    m2: 55,
    price: 1800,
    priceLabel: '1.800 €/mes',
    mode: 'alquiler',
    category: 'piso',
    tag: 'Destacado',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80',
    desc: 'Piso luminoso a dos pasos de la playa. Terraza con vistas al mar.',
    features: ['Terraza', 'Vistas al mar', 'Amueblado', 'Aire acondicionado'],
    floor: '3ª',
    coords: { lat: 41.3797, lng: 2.1912 },
  },
  {
    id: 14,
    city: 'Barcelona',
    zone: 'Barceloneta',
    title: 'Inversión en primera línea de playa',
    beds: 1,
    baths: 1,
    m2: 45,
    price: 310000,
    priceLabel: '310.000 €',
    mode: 'compra',
    category: 'piso',
    image: 'https://images.unsplash.com/photo-1559599101-f09722fb4948?auto=format&fit=crop&w=900&q=80',
    desc: 'Apartamento como inversión turística en primera línea. Gran rentabilidad.',
    features: ['Vistas al mar', 'Balcón', 'Reformado'],
    floor: '2ª',
    coords: { lat: 41.3812, lng: 2.1934 },
  },
  // ── El Born ─────────────────────────────────────────────────────────────────
  {
    id: 15,
    city: 'Barcelona',
    zone: 'El Born',
    title: 'Piso modernista en el corazón del Born',
    beds: 2,
    baths: 1,
    m2: 72,
    price: 420000,
    priceLabel: '420.000 €',
    mode: 'compra',
    category: 'piso',
    tag: 'Destacado',
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=900&q=80',
    desc: 'Piso modernista con detalles originales, techos de 3,5m y suelos hidráulicos.',
    features: ['Techos altos', 'Suelos hidráulicos', 'Balcón', 'Reformado'],
    floor: '3ª',
    coords: { lat: 41.3843, lng: 2.1812 },
  },
  {
    id: 16,
    city: 'Barcelona',
    zone: 'El Born',
    title: 'Estudio con encanto en alquiler',
    beds: 1,
    baths: 1,
    m2: 40,
    price: 1050,
    priceLabel: '1.050 €/mes',
    mode: 'alquiler',
    category: 'piso',
    image: 'https://images.unsplash.com/photo-1543489816-c05b3a71c98c?auto=format&fit=crop&w=900&q=80',
    desc: 'Estudio con mucho carácter en el barrio más cool de Barcelona.',
    features: ['Amueblado', 'Calefacción', 'Reformado'],
    floor: '1ª',
    coords: { lat: 41.3857, lng: 2.1789 },
  },
  // ── El Raval ────────────────────────────────────────────────────────────────
  {
    id: 17,
    city: 'Barcelona',
    zone: 'El Raval',
    title: 'Piso amplio a reformar, gran oportunidad',
    beds: 3,
    baths: 1,
    m2: 90,
    price: 220000,
    priceLabel: '220.000 €',
    mode: 'compra',
    category: 'piso',
    image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=900&q=80',
    desc: 'Piso a reformar en zona en plena transformación urbana. Gran potencial.',
    features: ['Techos altos', 'Balcón', 'A reformar'],
    floor: '4ª',
    coords: { lat: 41.3797, lng: 2.1677 },
  },
  {
    id: 18,
    city: 'Barcelona',
    zone: 'El Raval',
    title: 'Piso económico en alquiler',
    beds: 2,
    baths: 1,
    m2: 58,
    price: 850,
    priceLabel: '850 €/mes',
    mode: 'alquiler',
    category: 'piso',
    image: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=900&q=80',
    desc: 'Piso funcional y bien comunicado. Ideal para estudiantes o jóvenes profesionales.',
    features: ['Amueblado', 'Calefacción central'],
    floor: '2ª',
    coords: { lat: 41.3811, lng: 2.1658 },
  },
  // ── Pedralbes ───────────────────────────────────────────────────────────────
  {
    id: 19,
    city: 'Barcelona',
    zone: 'Pedralbes',
    title: 'Villa de lujo con piscina privada',
    beds: 6,
    baths: 4,
    m2: 420,
    price: 2800000,
    priceLabel: '2.800.000 €',
    mode: 'compra',
    category: 'chalet',
    tag: 'Exclusiva',
    image: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=900&q=80',
    desc: 'Imponente villa de lujo en la zona más exclusiva de Barcelona. Piscina, jardín y garaje.',
    features: ['Piscina', 'Jardín', 'Garaje 3 coches', 'Domótica', 'Alarma', 'Servicio'],
    coords: { lat: 41.3894, lng: 2.1118 },
  },
  // ── Nou Barris ──────────────────────────────────────────────────────────────
  {
    id: 20,
    city: 'Barcelona',
    zone: 'Nou Barris',
    title: 'Piso reformado con gran relación calidad-precio',
    beds: 3,
    baths: 2,
    m2: 80,
    price: 195000,
    priceLabel: '195.000 €',
    mode: 'compra',
    category: 'piso',
    image: 'https://images.unsplash.com/photo-1576941089067-2de3c901e126?auto=format&fit=crop&w=900&q=80',
    desc: 'Piso totalmente reformado en zona residencial tranquila. Muy buenas comunicaciones.',
    features: ['Ascensor', 'Parquet', 'Armarios empotrados', 'Garaje opcional'],
    floor: '3ª',
    coords: { lat: 41.4436, lng: 2.1761 },
  },
  // ── Sant Andreu ─────────────────────────────────────────────────────────────
  {
    id: 24,
    city: 'Barcelona',
    zone: 'Sant Andreu',
    title: 'Piso familiar en barrio tranquilo',
    beds: 4,
    baths: 2,
    m2: 95,
    price: 285000,
    priceLabel: '285.000 €',
    mode: 'compra',
    category: 'piso',
    image: 'https://images.unsplash.com/photo-1560184897-ae75f418493e?auto=format&fit=crop&w=900&q=80',
    desc: 'Piso espacioso en zona residencial con mucha vida de barrio. Cerca del mercado.',
    features: ['Ascensor', 'Balcón', 'Parquet', 'Trastero'],
    floor: '3ª',
    coords: { lat: 41.4337, lng: 2.1872 },
  },
  {
    id: 25,
    city: 'Barcelona',
    zone: 'Sant Andreu',
    title: 'Estudio en alquiler bien comunicado',
    beds: 1,
    baths: 1,
    m2: 35,
    price: 780,
    priceLabel: '780 €/mes',
    mode: 'alquiler',
    category: 'piso',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=900&q=80',
    desc: 'Estudio funcional a 5 minutos de metro y tren. Ideal para profesionales.',
    features: ['Amueblado', 'Reformado'],
    floor: '1ª',
    coords: { lat: 41.4355, lng: 2.1847 },
  },
  // ── Poblenou ────────────────────────────────────────────────────────────────
  {
    id: 26,
    city: 'Barcelona',
    zone: 'Poblenou',
    title: 'Loft en antiguo edificio industrial',
    beds: 2,
    baths: 1,
    m2: 130,
    price: 550000,
    priceLabel: '550.000 €',
    mode: 'compra',
    category: 'piso',
    tag: 'Nuevo',
    image: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=900&q=80',
    desc: 'Espectacular loft en edificio industrial reconvertido. Techos de 5m, vigas vistas.',
    features: ['Techos altos', 'Vigas vistas', 'Garaje', 'Terraza'],
    floor: '1ª',
    coords: { lat: 41.4012, lng: 2.2028 },
  },
  {
    id: 27,
    city: 'Barcelona',
    zone: 'Poblenou',
    title: 'Piso moderno en el 22@ en alquiler',
    beds: 2,
    baths: 2,
    m2: 75,
    price: 1500,
    priceLabel: '1.500 €/mes',
    mode: 'alquiler',
    category: 'piso',
    tag: 'Nuevo',
    image: 'https://images.unsplash.com/photo-1525438160292-a4a860951216?auto=format&fit=crop&w=900&q=80',
    desc: 'Piso de nueva construcción en el distrito tecnológico 22@. Eficiencia energética A.',
    features: ['Amueblado', 'Garaje', 'Domótica', 'Aire acondicionado'],
    floor: '5ª',
    coords: { lat: 41.4034, lng: 2.1991 },
  },
  // ── Vall d'Hebron ────────────────────────────────────────────────────────────
  {
    id: 28,
    city: "Barcelona",
    zone: "Vall d'Hebron",
    title: 'Piso con vistas al parque',
    beds: 3,
    baths: 2,
    m2: 88,
    price: 265000,
    priceLabel: '265.000 €',
    mode: 'compra',
    category: 'piso',
    image: 'https://images.unsplash.com/photo-1565183997392-2f6f122e5912?auto=format&fit=crop&w=900&q=80',
    desc: 'Piso tranquilo con vistas al Parc de la Vall d\'Hebron. Zona verde y silenciosa.',
    features: ['Terraza', 'Ascensor', 'Parquet'],
    floor: '3ª',
    coords: { lat: 41.4287, lng: 2.1455 },
  },
  // ── Sant Gervasi ────────────────────────────────────────────────────────────
  {
    id: 29,
    city: 'Barcelona',
    zone: 'Sant Gervasi',
    title: 'Piso señorial en zona alta',
    beds: 4,
    baths: 3,
    m2: 160,
    price: 890000,
    priceLabel: '890.000 €',
    mode: 'compra',
    category: 'piso',
    tag: 'Exclusiva',
    image: 'https://images.unsplash.com/photo-1515263487990-61b07816b324?auto=format&fit=crop&w=900&q=80',
    desc: 'Piso de gran prestancia en finca señorial. Techos de 4m, molduras originales.',
    features: ['Portero 24h', 'Garaje', 'Trastero', 'Parquet noble'],
    floor: '2ª',
    coords: { lat: 41.4013, lng: 2.1342 },
  },
  {
    id: 30,
    city: 'Barcelona',
    zone: 'Sant Gervasi',
    title: 'Piso en alquiler con parking incluido',
    beds: 3,
    baths: 2,
    m2: 100,
    price: 2000,
    priceLabel: '2.000 €/mes',
    mode: 'alquiler',
    category: 'piso',
    image: 'https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=900&q=80',
    desc: 'Piso amplio con garaje incluido en precio. Zona tranquila, cerca de colegios.',
    features: ['Garaje incluido', 'Amueblado', 'Aire acondicionado', 'Ascensor'],
    floor: '4ª',
    coords: { lat: 41.3997, lng: 2.1318 },
  },
]

export const mapPins: MapPin[] = properties
  .filter((p) => p.coords)
  .map((p, i) => ({
    id: p.id,
    priceLabel: p.mode === 'alquiler'
      ? `${(p.price / 1000).toFixed(0)}k/m`
      : p.price >= 1000000
        ? `${(p.price / 1000000).toFixed(1)}M`
        : `${Math.round(p.price / 1000)}k`,
    top: `${15 + (i % 5) * 14}%`,
    left: `${20 + (i % 6) * 12}%`,
  }))
