/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropiedadesIndexRouteImport } from './routes/propiedades/index'
import { Route as ServiciosSegurosRouteImport } from './routes/servicios/seguros'
import { Route as ServiciosHipotecasRouteImport } from './routes/servicios/hipotecas'
import { Route as ServiciosCambioDeSuministrosRouteImport } from './routes/servicios/cambio-de-suministros'
import { Route as ServiciosAdministracionDeFincasRouteImport } from './routes/servicios/administracion-de-fincas'
import { Route as PropiedadesIdRouteImport } from './routes/propiedades/$id'

const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesIndexRoute = PropiedadesIndexRouteImport.update({
  id: '/propiedades/',
  path: '/propiedades/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSegurosRoute = ServiciosSegurosRouteImport.update({
  id: '/servicios/seguros',
  path: '/servicios/seguros',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosHipotecasRoute = ServiciosHipotecasRouteImport.update({
  id: '/servicios/hipotecas',
  path: '/servicios/hipotecas',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosCambioDeSuministrosRoute =
  ServiciosCambioDeSuministrosRouteImport.update({
    id: '/servicios/cambio-de-suministros',
    path: '/servicios/cambio-de-suministros',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiciosAdministracionDeFincasRoute =
  ServiciosAdministracionDeFincasRouteImport.update({
    id: '/servicios/administracion-de-fincas',
    path: '/servicios/administracion-de-fincas',
    getParentRoute: () => rootRouteImport,
  } as any)
const PropiedadesIdRoute = PropiedadesIdRouteImport.update({
  id: '/propiedades/$id',
  path: '/propiedades/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/servicios/administracion-de-fincas': typeof ServiciosAdministracionDeFincasRoute
  '/servicios/cambio-de-suministros': typeof ServiciosCambioDeSuministrosRoute
  '/servicios/hipotecas': typeof ServiciosHipotecasRoute
  '/servicios/seguros': typeof ServiciosSegurosRoute
  '/propiedades/': typeof PropiedadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/servicios/administracion-de-fincas': typeof ServiciosAdministracionDeFincasRoute
  '/servicios/cambio-de-suministros': typeof ServiciosCambioDeSuministrosRoute
  '/servicios/hipotecas': typeof ServiciosHipotecasRoute
  '/servicios/seguros': typeof ServiciosSegurosRoute
  '/propiedades': typeof PropiedadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/servicios/administracion-de-fincas': typeof ServiciosAdministracionDeFincasRoute
  '/servicios/cambio-de-suministros': typeof ServiciosCambioDeSuministrosRoute
  '/servicios/hipotecas': typeof ServiciosHipotecasRoute
  '/servicios/seguros': typeof ServiciosSegurosRoute
  '/propiedades/': typeof PropiedadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/nosotros'
    | '/propiedades/$id'
    | '/servicios/administracion-de-fincas'
    | '/servicios/cambio-de-suministros'
    | '/servicios/hipotecas'
    | '/servicios/seguros'
    | '/propiedades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/nosotros'
    | '/propiedades/$id'
    | '/servicios/administracion-de-fincas'
    | '/servicios/cambio-de-suministros'
    | '/servicios/hipotecas'
    | '/servicios/seguros'
    | '/propiedades'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/nosotros'
    | '/propiedades/$id'
    | '/servicios/administracion-de-fincas'
    | '/servicios/cambio-de-suministros'
    | '/servicios/hipotecas'
    | '/servicios/seguros'
    | '/propiedades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  NosotrosRoute: typeof NosotrosRoute
  PropiedadesIdRoute: typeof PropiedadesIdRoute
  ServiciosAdministracionDeFincasRoute: typeof ServiciosAdministracionDeFincasRoute
  ServiciosCambioDeSuministrosRoute: typeof ServiciosCambioDeSuministrosRoute
  ServiciosHipotecasRoute: typeof ServiciosHipotecasRoute
  ServiciosSegurosRoute: typeof ServiciosSegurosRoute
  PropiedadesIndexRoute: typeof PropiedadesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades/': {
      id: '/propiedades/'
      path: '/propiedades'
      fullPath: '/propiedades/'
      preLoaderRoute: typeof PropiedadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/seguros': {
      id: '/servicios/seguros'
      path: '/servicios/seguros'
      fullPath: '/servicios/seguros'
      preLoaderRoute: typeof ServiciosSegurosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/hipotecas': {
      id: '/servicios/hipotecas'
      path: '/servicios/hipotecas'
      fullPath: '/servicios/hipotecas'
      preLoaderRoute: typeof ServiciosHipotecasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/cambio-de-suministros': {
      id: '/servicios/cambio-de-suministros'
      path: '/servicios/cambio-de-suministros'
      fullPath: '/servicios/cambio-de-suministros'
      preLoaderRoute: typeof ServiciosCambioDeSuministrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/administracion-de-fincas': {
      id: '/servicios/administracion-de-fincas'
      path: '/servicios/administracion-de-fincas'
      fullPath: '/servicios/administracion-de-fincas'
      preLoaderRoute: typeof ServiciosAdministracionDeFincasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades/$id': {
      id: '/propiedades/$id'
      path: '/propiedades/$id'
      fullPath: '/propiedades/$id'
      preLoaderRoute: typeof PropiedadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  NosotrosRoute: NosotrosRoute,
  PropiedadesIdRoute: PropiedadesIdRoute,
  ServiciosAdministracionDeFincasRoute: ServiciosAdministracionDeFincasRoute,
  ServiciosCambioDeSuministrosRoute: ServiciosCambioDeSuministrosRoute,
  ServiciosHipotecasRoute: ServiciosHipotecasRoute,
  ServiciosSegurosRoute: ServiciosSegurosRoute,
  PropiedadesIndexRoute: PropiedadesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
